// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtnH4f09g6Mk7zyipJvMESbYtlNHrPBzk',
    appId: '1:798117686946:web:443ef54af2dce3b899b1fb',
    messagingSenderId: '798117686946',
    projectId: 'horta-monitorada1',
    authDomain: 'horta-monitorada1.firebaseapp.com',
    databaseURL: 'https://horta-monitorada1-default-rtdb.firebaseio.com',
    storageBucket: 'horta-monitorada1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMA7T-zSicNULAbhlGbMGlPeCKrs7mxvs',
    appId: '1:798117686946:android:428e973c8202a1c599b1fb',
    messagingSenderId: '798117686946',
    projectId: 'horta-monitorada1',
    databaseURL: 'https://horta-monitorada1-default-rtdb.firebaseio.com',
    storageBucket: 'horta-monitorada1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9PNdSWSSCh3mms7CLW9dJyQTquBO-qQ0',
    appId: '1:798117686946:ios:40697422701d020e99b1fb',
    messagingSenderId: '798117686946',
    projectId: 'horta-monitorada1',
    databaseURL: 'https://horta-monitorada1-default-rtdb.firebaseio.com',
    storageBucket: 'horta-monitorada1.appspot.com',
    iosClientId: '798117686946-j9gl2m7fa4guegpptvg8m5ejdn6f7mc1.apps.googleusercontent.com',
    iosBundleId: 'com.example.jardimApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9PNdSWSSCh3mms7CLW9dJyQTquBO-qQ0',
    appId: '1:798117686946:ios:40697422701d020e99b1fb',
    messagingSenderId: '798117686946',
    projectId: 'horta-monitorada1',
    databaseURL: 'https://horta-monitorada1-default-rtdb.firebaseio.com',
    storageBucket: 'horta-monitorada1.appspot.com',
    iosClientId: '798117686946-j9gl2m7fa4guegpptvg8m5ejdn6f7mc1.apps.googleusercontent.com',
    iosBundleId: 'com.example.jardimApp',
  );
}
